YouStore-Local databse/YouStore/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using YouStore.ViewsModels;
using YouStorePro.ViewsModels;

namespace YouStore.Controllers
{
    public class ClientController : Controller
    {
        ClientLogic ClientLogic = new ClientLogic();

        Client client = new Client();

        public IActionResult Index()
        {
            return View();
        }

  

        public ActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
         

            foreach (var i in ClientLogic.GetAllUsers())
            {
                
                if (i.Email == model.Email && i.Password == model.Password)
                {
                    if (i.IsAdmin)
                    { return RedirectToAction("AdminHome", "Admin"); }
                    else
                    {
                        HttpContext.Session.SetString("Firstname", i.UserFirstName);
                        HttpContext.Session.SetString("Email", i.Email);
                        HttpContext.Session.SetInt32("ClientId", i.Id);
                       
                        
                        
                        return RedirectToAction("HomeClient", "Home");
                    }
                    
                }
                
                
            }
            return View(model);
        }
        public ActionResult ProductenKopen()
        {
            int? ClientId = HttpContext.Session.GetInt32("ClientId");
            string UserEmail = HttpContext.Session.GetString("Email");
            string UserFirstName = HttpContext.Session.GetString("Firstname");
  
            ShoppingBasketLogic  basket = new ShoppingBasketLogic();
            foreach (Product i in ClientLogic.GetAllProductsForUser(Convert.ToInt32(ClientId)))
            {
                ClientLogic.SetOrder(Convert.ToInt32(ClientId), i.ProductId, UserEmail, UserFirstName);
            }

            return RedirectToAction("HomeClient", "Home");
        }
        public ActionResult OrdersList()
        {
            int? ClientId = HttpContext.Session.GetInt32("ClientId");
            
            

         



            return View(ClientLogic.GetAllOrders(Convert.ToInt32(ClientId)));
        }


        public ActionResult ClientProfile()
        {
            int? ClientId = HttpContext.Session.GetInt32("ClientId");
            
            List<Client> Clients = ClientLogic.GetAllUsers();
            
            
            foreach (Client C in Clients)
            {
                if (C.Id == Convert.ToInt32(ClientId))
                {
                    client = C;
                    break;
                }
            }


            return View(client);
        }
        public IActionResult EditClientProfile()
        {

            int? ClientId = HttpContext.Session.GetInt32("ClientId");
            
            List<Client> Clients = ClientLogic.GetAllUsers();
            

            foreach (Client C in Clients)
            {
                if (C.Id == Convert.ToInt32(ClientId))
                {
                    client = C;
                    break;
                }
            }


            EditPersonelInformation model = new EditPersonelInformation();
            model.UserFirstName = client.UserFirstName;
            model.UserLastName = client.UserLastName;
            model.Email = client.Email;
            model.City = client.City;
            model.State = client.State;
            model.PostalCode = client.PostalCode;
            model.Phone = client.Phone;
            model.Street = client.Street;
            model.Country = client.Country;
            return View(model);
        }

        [HttpPost]
        public IActionResult EditClientProfile(EditPersonelInformation model)
        {
            int? clientId = HttpContext.Session.GetInt32("ClientId");

            int ClientId = Convert.ToInt32(clientId);



            ClientLogic.EditClientProfile(ClientId,model.UserFirstName,model.Email, model.UserLastName,model.City,model.Street,model.State,model.Phone,model.PostalCode,model.Country);




            return RedirectToAction("ClientProfile");
        }
        public ActionResult DeletAccount()
        {
            int? ClientId = HttpContext.Session.GetInt32("ClientId");



            ClientLogic.DeletAccount(Convert.ToInt32(ClientId));


            return RedirectToAction("Login");
        }



    }
}

YouStore-Local databse/YouStore/Controllers/UserCollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Models;
using Logic;
using Microsoft.AspNetCore.Http;

namespace YouStore.Controllers
{
    public class UserCollectionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult SingUp(User model)
        {
            return View(model);
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult singUp(User model)
        {
          
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            ClientLogic clientlogic = new ClientLogic();
            foreach ( User user in clientlogic.GetAllUsers() )
            {
                if (model.Email == user.Email)
                {
                    ViewBag.message = "Dit Email heeft al een account !";
                    return View(model);
                }
            }

            UserCollectionlogic userCollectionLogic = new UserCollectionlogic(model);
            userCollectionLogic.SignUp(model);
            userCollectionLogic.SendWelcomMail(model.Email, model.UserFirstName);

            return RedirectToAction("Index", "Home");
        }
        

    }
}

YouStore-Local databse/YouStore/Views/Client/ClientProfile.cshtml
@model Models.Client

@{
    ViewData["Title"] = "ClientProfile";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}
<body>


    <div class="card">
        <img src="~/images/Ninja.png" alt="John" style="width:100%">
        <h1>@Html.DisplayFor(model => model.UserFirstName) @Html.DisplayFor(model => model.UserLastName)</h1>
        <h1>@Html.DisplayFor(model => model.Email)</h1>
        <p class="title">@Html.DisplayFor(model => model.Phone)</p>
        <p>@Html.DisplayFor(model => model.Street)</p>
        <p>@Html.DisplayFor(model => model.City)</p>
        <p>@Html.DisplayFor(model => model.State)</p>
        <p>@Html.DisplayFor(model => model.PostalCode)</p>

        <div style="margin: 24px 0;">
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a class="Delet" asp-area="" asp-controller="Client" asp-action="DeletAccount">Delet account</a>
        </div>
        <p><button onclick="location.href='/Client/EditClientProfile'">Editie Profile</button></p>
        
</body>


    </div>
<style>
    .Delet
    {
        color : red;
    }


    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        margin: auto;
        text-align: center;
        font-family: arial;
    }

    .title {
        color: grey;
        font-size: 18px;
    }

    button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

    a {
        text-decoration: none;
        font-size: 22px;
        color: black;
    }

        button:hover, a:hover {
            opacity: 0.7;
        }
</style>

YouStore-Local databse/YouStore/Views/Client/EditClientProfile.cshtml
@model YouStore.ViewsModels.EditPersonelInformation

@{
    ViewData["Title"] = "EditClientProfile";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<h2>EditClientProfile</h2>

<h4>EditPersonelInformation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditClientProfile">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserFirstName" class="control-label"></label>
                <input asp-for="UserFirstName" class="form-control" />
                <span asp-validation-for="UserFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserLastName" class="control-label"></label>
                <input asp-for="UserLastName" class="form-control" />
                <span asp-validation-for="UserLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

YouStore-Local databse/YouStore/Views/Client/Login.cshtml
@model YouStorePro.ViewsModels.LoginViewModel

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>

<h4>LoginViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="creat" asp-controller="UserCollection" asp-action="singUp">Creat account!</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<style>
.creat{
    color: blue;
}
</style>

YouStore-Local databse/YouStore/Views/Client/OrdersList.cshtml
@model IEnumerable<Models.Product>

@{
    ViewData["Title"] = "OrdersList";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<h2>OrdersList</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrijs)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrijs)
            </td>

        </tr>
}
    </tbody>
</table>